FROM ubuntu:14.04

MAINTAINER Daniel Mazzer "daniel@bviot.com.br"

RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:webupd8team/java -y
RUN apt-get update
RUN echo oracle-java7-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
RUN apt-get install -y \
	oracle-java8-installer \
	git \
	ant
RUN apt-get clean

#RUN apt-get update && apt-get install -y firefox

# Make ssh dir
RUN mkdir /root/.ssh/

# Replace 1000 with your user / group id
RUN export uid=1000 gid=1000 && \
    mkdir -p /home/developer && \
    echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
    echo "developer:x:${uid}:" >> /etc/group && \
    echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
    chmod 0440 /etc/sudoers.d/developer && \
    chown ${uid}:${gid} -R /home/developer

USER developer
ENV HOME /home/developer
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

#CMD /usr/bin/firefox

# Clone the conf files into the docker container
RUN git clone https://github.com/bviot/contiki.git --recursive /home/developer/contiki

CMD cd /home/developer/contiki/tools/cooja
CMD ant run

